# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e6d2b97c28b801d62d46af6b1fd632093bf2c561414fb047f2d193182dfeb96a75219dc0df2fb0ec3fe978b44c5827f2b4a400925546ffaa218e300d81253c6

test:
  secret_key_base: f65d8c6b1150745ca37f9a0c89f59d7adb0eac1eb53e3b0f745bff9a4987d2710bf428ff4c266ff150c5e4e05aeec2897c0cd1eb159a3cb462c708ea69ea0df4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
